INSERT INTO Vehicles (PlateNumber, OwnerName, RegistrationStatus, Model) VALUES
('GT-12342-24', 'Kwame Appiah', 'Active', 'Toyota Corolla'),
('GR-5678-23', 'Ama Boateng', 'Expired', 'Nissan Sentra'),
('GT-9012-22', 'Kofi Mensah', 'Active', 'Kantanka Omama'),
('GR-3456-25', 'Abena Osei', 'Active', 'Toyota Camry'),
('GT-7890-22', 'Yaw Asante', 'Expired', 'Honda Civic'),
('GR-1122-21', 'Akua Addo', 'Active', 'Nissan Altima'),
('GT-3344-20', 'Kwesi Amoako', 'Expired', 'Ford Escape'),
('GR-5566-24', 'Adwoa Gyamfi', 'Active', 'Kantanka Otumfuo'),
('GT-7788-22', 'Kojo Antwi', 'Active', 'Toyota RAV4'),
('GR-9900-19', 'Efua Dankwa', 'Expired', 'Suzuki Swift'),
('GT-1213-25', 'Kwadwo Baidoo', 'Active', 'Nissan Patrol'),
('GR-1415-23', 'Maame Yaa', 'Expired', 'Honda Accord'),
('GT-1617-18', 'Nana Kwame', 'Active', 'Kantanka Amoanimaa'),
('GR-1819-25', 'Esi Koranteng', 'Active', 'Toyota Hilux'),
('GT-2021-24', 'Osei Tutu', 'Expired', 'Volkswagen Golf'),
('GR-2223-21', 'Kwabena Owusu', 'Active', 'Nissan X-Trail'),
('GT-2425-22', 'Agyeiwaa Agyeman', 'Expired', 'Ford Ranger'),
('GR-2627-20', 'Opoku Ware', 'Active', 'Kantanka Kobby'),
('GT-2829-20', 'Serwaa Bonsu', 'Active', 'Toyota Yaris'),
('GR-3031-21', 'Kweku Annan', 'Expired', 'Suzuki Vitara'),
('GT-3233-22', 'Afia Sarkodie', 'Active', 'Nissan Qashqai'),
('GR-3435-24', 'Papa Yaw', 'Expired', 'Honda CR-V'),
('GT-3637-23', 'Nana Adwoa', 'Active', 'Kantanka Adom'),
('GR-3839-25', 'Kwame Nkrumah', 'Active', 'Toyota Land Cruiser'),
('GT-4041-20', 'Ama Nyarko', 'Expired', 'Volkswagen Tiguan'),
('GR-4243-25', 'Kofi Gyan', 'Active', 'Nissan Juke'),
('GT-44450-22', 'Abena Frimpong', 'Expired', 'Ford Explorer'),
('GR-4647-24', 'Yaw Duah', 'Active', 'Kantanka Blade'),
('GT-4849-21', 'Akosua Amponsah', 'Active', 'Toyota Prado'),
('GR-5051-21', 'Kojo Adu', 'Expired', 'Suzuki Grand Vitara');