INSERT INTO Vehicles (PlateNumber, OwnerName, RegistrationStatus, Model) VALUES
('GT-1234', 'Kwame Appiah', 'Active', 'Toyota Corolla'),
('GR-5678', 'Ama Boateng', 'Expired', 'Nissan Sentra'),
('GT-9012', 'Kofi Mensah', 'Active', 'Mercedes Benz'),
('GR-3456', 'Abena Osei', 'Active', 'Toyota Camry'),
('GT-7890', 'Yaw Asante', 'Expired', 'Honda Civic'),
('GR-1122', 'Akua Addo', 'Active', 'Nissan Altima'),
('GT-3344', 'Kwesi Amoako', 'Expired', 'Ford Escape'),
('GR-5566', 'Adwoa Gyamfi', 'Active', 'Kantanka Otumfuo'),
('GT-7788', 'Kojo Antwi', 'Active', 'Toyota RAV4'),
('GR-9900', 'Efua Dankwa', 'Expired', 'Suzuki Swift'),
('GT-1213', 'Kwadwo Baidoo', 'Active', 'Nissan Patrol'),
('GR-1415', 'Maame Yaa', 'Expired', 'Honda Accord'),
('GT-1617', 'Nana Kwame', 'Active', 'Kantanka Amoanimaa'),
('GR-1819', 'Esi Koranteng', 'Active', 'Toyota Hilux'),
('GT-2021', 'Osei Tutu', 'Expired', 'Volkswagen Golf'),
('GR-2223', 'Kwabena Owusu', 'Active', 'Nissan X-Trail'),
('GT-2425', 'Agyeiwaa Agyeman', 'Expired', 'Ford Ranger'),
('GR-2627', 'Opoku Ware', 'Active', 'BMW'),
('GT-2829', 'Serwaa Bonsu', 'Active', 'Toyota Yaris'),
('GR-3031', 'Kweku Annan', 'Expired', 'Suzuki Vitara'),
('GT-3233', 'Afia Sarkodie', 'Active', 'Nissan Qashqai'),
('GR-3435', 'Papa Yaw', 'Expired', 'Honda CR-V'),
('GT-3637', 'Nana Adwoa', 'Active', 'Range Rover'),
('GR-3839', 'Kwame Nkrumah', 'Active', 'Toyota Land Cruiser'),
('GT-4041', 'Ama Nyarko', 'Expired', 'Volkswagen Tiguan'),
('GR-4243', 'Kofi Gyan', 'Active', 'Nissan Juke'),
('GT-4445', 'Abena Frimpong', 'Expired', 'Ford Explorer'),
('GR-4647', 'Yaw Duah', 'Active', 'Lamborghini'),
('GT-4849', 'Akosua Amponsah', 'Active', 'Toyota Prado'),
('GR-5051', 'Kojo Adu', 'Expired', 'Suzuki Grand Vitara');